# Generated by Django 5.0.7 on 2025-01-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='coin',
            field=models.IntegerField(default=0),
        ),
    ]
