# Generated by Django 5.0.7 on 2025-01-05 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
